export const localChatLogsModel: Record<string, string> = {
  client_msg_id: 'char(64)',
  server_msg_id: 'char(64)',
  send_id: 'char(64)',
  recv_id: 'char(64)',
  sender_platform_id: 'integer',
  sender_nick_name: 'varchar(255)',
  sender_face_url: 'varchar(255)',
  session_type: 'integer',
  msg_from: 'integer',
  content_type: 'integer',
  content: 'varchar(1000)',
  is_read: 'numeric',
  status: 'integer',
  seq: 'integer default 0',
  send_time: 'integer',
  create_time: 'integer',
  attached_info: 'varchar(1024)',
  ex: 'varchar(1024)',
  is_react: 'numeric',
  is_external_extensions: 'numeric',
  msg_first_modify_time: 'integer',
};
