import { Database, QueryExecResult } from '@jlongster/sql.js';

export type LocalTableMaster = { [key: string]: any };

// Init Table Tips:
// This table is automatically generated by sqlite and does not need to be manually created!
export function getExistedTables(db: Database): QueryExecResult[] {
  return db.exec(
    `
      SELECT name FROM sqlite_master WHERE type="table";
    `
  );
}
